### ISSUE TITLE
Corrupt Quill parchment results in data loss when editing (seems specific to IE)

### ISSUE THREAD

**Issue by anindara** [quilljs/parchment#14] opened 2016-10-07 00:28 UTC
https://github.com/quilljs/quill/issues/1028  tracks this on the Quill side, but opening this since it seems to manifest in the parchment. 

Steps to reproduce the problem:
1. Visit http://quilljs.com/playground
2. Copy the text non-column text blocks from http://lipsum.com/ [START with the header "The standard Lorem Ipsum passage, used since the 1500s" and END at "to avoid worse pains." before the help@limpsum.com block]
3. Use Ctrl + Backspace to remove 3 words ("Unable to get property 'mutations' of undefined or null reference" shows up in the console at blot.update(blot.domNode[Registry.DATA_KEY].mutations || []);). Then Ctrl + Z to undo 2 times (See "Unable to get property 'length' of undefined or null reference" now in the console on keydown var curContext = { range...)
   Expected behavior: Words are re-added back one by one until we get back to full paragraph

Actual behavior: After 2nd redo, the whole paragraph disappears and "Cannot read property 'mutations' of undefined" throws at

Platforms: IE 11.0.9600.18450 windows 10, 8 or 2012 R2

Include browser, operating system and respective versions

Version: 1.0.6

Note: This isn't limited to just Ctrl + Z/Backspace and is non-deterministic. I am able to reproduce while performing simple edit operations.

The problem seems to be that the TextBlot is getting corrupted, with its domNode not attached to a __blot. This results in a null reference when trying to access the mutations in the blot's domNode when trying to update the ScrollBlot, This puts the parchment in a weird state resulting in exceptions in followup keydown events (where the scroll lines are no longer defined, ranges are inconsistent etc.). This continues until the new ContainerBlot is created on Enter. 

![image](https://cloud.githubusercontent.com/assets/22333452/19175074/a05f5918-8be8-11e6-971a-e82771174655.png)

CallStack trace:
![image](https://cloud.githubusercontent.com/assets/22333452/19175168/57a1f112-8be9-11e6-8e37-bf428beb2cf6.png)

![image](https://cloud.githubusercontent.com/assets/22333452/19175183/733d6dc0-8be9-11e6-8f88-19a58dc66b01.png)

![image](https://cloud.githubusercontent.com/assets/22333452/19175191/83f323bc-8be9-11e6-85a0-b59299a1efc9.png)

The TextBlot in question:

![image](https://cloud.githubusercontent.com/assets/22333452/19175294/4246bca2-8bea-11e6-830b-8997b8aefad2.png)

**Comment by anindara** [comment] 2016-10-07 22:59
A few more points. (while this isn't limited to a particular mutation): Ctrl+BackSpace results in IE emitting ‘childList’ mutations (among others), while Chrome emits ‘characterData’ mutations. (enclose is a snip of the mutation record in IE)

![image](https://cloud.githubusercontent.com/assets/22333452/19207501/6d51eba8-8ca6-11e6-9de5-e9b327a63cd8.png)

The ContainerBlot update looks at this MutationRecord, finds that the text node needs to be removed, and thereby detaches it. This results in an inconsistency between the parchment and the DOM resulting in things like losing the entire paragraph (associated with that TextBlot), losing ability to track selection on this paragraph etc. (as pointed out above). Hope this helps.

**Comment by jhchen** [comment] 2016-10-12 06:24
Thanks for the details. It looks like the root issue is IE11 reporting incorrect mutation records. From this [fiddle](https://jsfiddle.net/jhchen/wLssjuw5/7/), place your cursor at the end of the line in IE11, control backspace quickly. You will see text nodes reported being deleted when in fact they have not. This is why Quill thinks text got deleted.

**Comment by jhchen** [comment] 2016-10-17 01:05
Another example is if you:

1. Visit this [fiddle](https://jsfiddle.net/jhchen/wLssjuw5/7/) in IE11
2. Place cursor at the end of the line
3. type test@gmail.com
4. Hit space

IE11 will report two mutations, one saying the text 'aa bb cc dd ee test@gmail.com' turned into test@gmail.com and another saying the anchor tag has been added. This is incorrect since 'aa bb cc dd ee' is still present in the container.

**Comment by nickbaum** [comment] 2016-12-26 04:42
Ah, I think some of my customers might have run into this, though I haven't been able to reproduce it.

I see the bug is still open – is it not fixed as of 1.1.8?

**Comment by jhchen** [comment] 2016-12-27 22:26
Yes open means not fixed.

The original reported issue of control + delete is worked around in Quill through keyboard handlers but not Parchment since there's no IO abstraction. But the additional auto linking case I added is not fixed or worked around in either. It appears, from the two fiddles linked (which do not use Quill), that IE11 mutation observer implementation suffers from both false positives and false negatives. The latter makes it impossible to rely on mutation observers for tracking changes.

**Comment by nickbaum** [comment] 2016-12-27 22:36
Ugh, sorry to hear that. I may have to disable Quill in IE for now, as it seems to be coming up fairly frequently for my customers.

Do you have an idea for how to fix it, or is it likely to stay open for a while?

**Comment by jhchen** [comment] 2016-12-27 22:59
A real fix does not seem likely without changes from IE since the false negative issue means it does not get information that it needs. Workarounds for specific scenarios is probably more likely, like how the original control + delete was worked around, but I have not been able to figure out how to disable auto linking. `document.execCommand(“AutoUrlDetect”, false, false)` apparently was added in IE9 but it does not appear to do anything in IE11. If anyone has any insight please feel free to share.

**Comment by nickbaum** [comment] 2016-12-27 23:30
Yeah, I see how that's tricky. I doubt my customers are running into linkification, so I'll have to see if I can figure out a more precise repro case. Anecdotally I think it may have to do with delete and undo.

Since this seems to lead to loss of data, I wonder if it makes sense to mark Quill as not being compatible with IE11 for now.

As always, thanks for your hard work.

**Comment by jhchen** [comment] 2016-12-29 04:14
I haven't given up yet on finding a workaround but it may come to that.

**Comment by nickbaum** [comment] 2016-12-30 23:42
Fair enough. I've disabled Quill in IE for now, but I'll see if I can find some time to try and repro.

**Closed** 2017-01-02 04:27 UTC
